# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct UserApi <: OpenAPIClient.APIImpl
    client::OpenAPIClient.Client
end

function _oacinternal_createUser(_api::UserApi, User; _mediaType=nothing)
    _ctx = OpenAPIClient.Ctx(_api.client, "POST", Nothing, "/user", [], User)
    OpenAPIClient.set_header_accept(_ctx, [])
    OpenAPIClient.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Create user

This can only be done by the logged in user.

Params:
- User::User (required)

Return: Nothing
"""
function createUser(_api::UserApi, User; _mediaType=nothing)
    _ctx = _oacinternal_createUser(_api, User; _mediaType=_mediaType)
    OpenAPIClient.exec(_ctx)
end

function createUser(_api::UserApi, response_stream::Channel, User; _mediaType=nothing)
    _ctx = _oacinternal_createUser(_api, User; _mediaType=_mediaType)
    OpenAPIClient.exec(_ctx, response_stream)
end

function _oacinternal_createUsersWithArrayInput(_api::UserApi, User; _mediaType=nothing)
    _ctx = OpenAPIClient.Ctx(_api.client, "POST", Nothing, "/user/createWithArray", [], User)
    OpenAPIClient.set_header_accept(_ctx, [])
    OpenAPIClient.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Creates list of users with given input array

Params:
- User::Vector{User} (required)

Return: Nothing
"""
function createUsersWithArrayInput(_api::UserApi, User; _mediaType=nothing)
    _ctx = _oacinternal_createUsersWithArrayInput(_api, User; _mediaType=_mediaType)
    OpenAPIClient.exec(_ctx)
end

function createUsersWithArrayInput(_api::UserApi, response_stream::Channel, User; _mediaType=nothing)
    _ctx = _oacinternal_createUsersWithArrayInput(_api, User; _mediaType=_mediaType)
    OpenAPIClient.exec(_ctx, response_stream)
end

function _oacinternal_createUsersWithListInput(_api::UserApi, User; _mediaType=nothing)
    _ctx = OpenAPIClient.Ctx(_api.client, "POST", Nothing, "/user/createWithList", [], User)
    OpenAPIClient.set_header_accept(_ctx, [])
    OpenAPIClient.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Creates list of users with given input array

Params:
- User::Vector{User} (required)

Return: Nothing
"""
function createUsersWithListInput(_api::UserApi, User; _mediaType=nothing)
    _ctx = _oacinternal_createUsersWithListInput(_api, User; _mediaType=_mediaType)
    OpenAPIClient.exec(_ctx)
end

function createUsersWithListInput(_api::UserApi, response_stream::Channel, User; _mediaType=nothing)
    _ctx = _oacinternal_createUsersWithListInput(_api, User; _mediaType=_mediaType)
    OpenAPIClient.exec(_ctx, response_stream)
end

function _oacinternal_deleteUser(_api::UserApi, username::String; _mediaType=nothing)
    _ctx = OpenAPIClient.Ctx(_api.client, "DELETE", Nothing, "/user/{username}", [])
    OpenAPIClient.set_param(_ctx.path, "username", username)  # type String
    OpenAPIClient.set_header_accept(_ctx, [])
    OpenAPIClient.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Delete user

This can only be done by the logged in user.

Params:
- username::String (required)

Return: Nothing
"""
function deleteUser(_api::UserApi, username::String; _mediaType=nothing)
    _ctx = _oacinternal_deleteUser(_api, username; _mediaType=_mediaType)
    OpenAPIClient.exec(_ctx)
end

function deleteUser(_api::UserApi, response_stream::Channel, username::String; _mediaType=nothing)
    _ctx = _oacinternal_deleteUser(_api, username; _mediaType=_mediaType)
    OpenAPIClient.exec(_ctx, response_stream)
end

function _oacinternal_getUserByName(_api::UserApi, username::String; _mediaType=nothing)
    _ctx = OpenAPIClient.Ctx(_api.client, "GET", User, "/user/{username}", [])
    OpenAPIClient.set_param(_ctx.path, "username", username)  # type String
    OpenAPIClient.set_header_accept(_ctx, ["application/xml", "application/json", ])
    OpenAPIClient.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Get user by user name

Params:
- username::String (required)

Return: User
"""
function getUserByName(_api::UserApi, username::String; _mediaType=nothing)
    _ctx = _oacinternal_getUserByName(_api, username; _mediaType=_mediaType)
    OpenAPIClient.exec(_ctx)
end

function getUserByName(_api::UserApi, response_stream::Channel, username::String; _mediaType=nothing)
    _ctx = _oacinternal_getUserByName(_api, username; _mediaType=_mediaType)
    OpenAPIClient.exec(_ctx, response_stream)
end

function _oacinternal_loginUser(_api::UserApi, username::String, password::String; _mediaType=nothing)
    _ctx = OpenAPIClient.Ctx(_api.client, "GET", String, "/user/login", [])
    OpenAPIClient.set_param(_ctx.query, "username", username)  # type String
    OpenAPIClient.set_param(_ctx.query, "password", password)  # type String
    OpenAPIClient.set_header_accept(_ctx, ["application/xml", "application/json", ])
    OpenAPIClient.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    @info("returning loginUser context", _ctx.query, _ctx.header, _ctx.return_type)
    return _ctx
end

@doc raw"""Logs user into the system

Params:
- username::String (required)
- password::String (required)

Return: String
"""
function loginUser(_api::UserApi, username::String, password::String; _mediaType=nothing)
    @info("loginUser called", username, password)
    _ctx = _oacinternal_loginUser(_api, username, password; _mediaType=_mediaType)
    OpenAPIClient.exec(_ctx)
end

function loginUser(_api::UserApi, response_stream::Channel, username::String, password::String; _mediaType=nothing)
    _ctx = _oacinternal_loginUser(_api, username, password; _mediaType=_mediaType)
    OpenAPIClient.exec(_ctx, response_stream)
end

function _oacinternal_logoutUser(_api::UserApi; _mediaType=nothing)
    _ctx = OpenAPIClient.Ctx(_api.client, "GET", Nothing, "/user/logout", [])
    OpenAPIClient.set_header_accept(_ctx, [])
    OpenAPIClient.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Logs out current logged in user session

Params:

Return: Nothing
"""
function logoutUser(_api::UserApi; _mediaType=nothing)
    _ctx = _oacinternal_logoutUser(_api; _mediaType=_mediaType)
    OpenAPIClient.exec(_ctx)
end

function logoutUser(_api::UserApi, response_stream::Channel; _mediaType=nothing)
    _ctx = _oacinternal_logoutUser(_api; _mediaType=_mediaType)
    OpenAPIClient.exec(_ctx, response_stream)
end

function _oacinternal_updateUser(_api::UserApi, username::String, User; _mediaType=nothing)
    _ctx = OpenAPIClient.Ctx(_api.client, "PUT", Nothing, "/user/{username}", [], User)
    OpenAPIClient.set_param(_ctx.path, "username", username)  # type String
    OpenAPIClient.set_header_accept(_ctx, [])
    OpenAPIClient.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Updated user

This can only be done by the logged in user.

Params:
- username::String (required)
- User::User (required)

Return: Nothing
"""
function updateUser(_api::UserApi, username::String, User; _mediaType=nothing)
    _ctx = _oacinternal_updateUser(_api, username, User; _mediaType=_mediaType)
    OpenAPIClient.exec(_ctx)
end

function updateUser(_api::UserApi, response_stream::Channel, username::String, User; _mediaType=nothing)
    _ctx = _oacinternal_updateUser(_api, username, User; _mediaType=_mediaType)
    OpenAPIClient.exec(_ctx, response_stream)
end

export createUser
export createUsersWithArrayInput
export createUsersWithListInput
export deleteUser
export getUserByName
export loginUser
export logoutUser
export updateUser
