# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Describes the result of uploading an image resource

    ApiResponse(;
        code=nothing,
        type=nothing,
        message=nothing,
    )

    - code::Int32
    - type::String
    - message::String
"""
Base.@kwdef mutable struct ApiResponse <: OpenAPIClient.APIModel
    code = nothing # spec type: Union{ Nothing, Int32 }
    type = nothing # spec type: Union{ Nothing, String }
    message = nothing # spec type: Union{ Nothing, String }

    function ApiResponse(code, type, message, )
        validate_property(ApiResponse, Symbol("code"), code)
        validate_property(ApiResponse, Symbol("type"), type)
        validate_property(ApiResponse, Symbol("message"), message)
        return new(code, type, message, )
    end
end # type ApiResponse

const _property_types_ApiResponse = Dict{Symbol,String}(Symbol("code")=>"Int32", Symbol("type")=>"String", Symbol("message")=>"String", )
OpenAPIClient.property_type(::Type{ ApiResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ApiResponse[name]))}

function check_required(o::ApiResponse)
    true
end

function validate_property(::Type{ ApiResponse }, name::Symbol, val)
end
