# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""A tag for a pet

    Tag(;
        id=nothing,
        name=nothing,
    )

    - id::Int64
    - name::String
"""
mutable struct Tag <: OpenAPIClient.APIModel
    id::Any # spec type: Union{ Nothing, Int64 } # spec name: id
    name::Any # spec type: Union{ Nothing, String } # spec name: name

    function Tag(;id=nothing, name=nothing, )
        o = new()
        validate_property(Tag, Symbol("id"), id)
        setfield!(o, Symbol("id"), id)
        validate_property(Tag, Symbol("name"), name)
        setfield!(o, Symbol("name"), name)
        o
    end
end # type Tag

const _property_map_Tag = Dict{Symbol,Symbol}(Symbol("id")=>Symbol("id"), Symbol("name")=>Symbol("name"), )
const _property_types_Tag = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("name")=>"String", )
Base.propertynames(::Type{ Tag }) = collect(keys(_property_map_Tag))
OpenAPIClient.property_type(::Type{ Tag }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Tag[name]))}
OpenAPIClient.field_name(::Type{ Tag }, property_name::Symbol) =  _property_map_Tag[property_name]

function check_required(o::Tag)
    true
end

function validate_property(::Type{ Tag }, name::Symbol, val)
end
